org: charles00willian
app: image-analysis
service: image-analysis

frameworkVersion: '2'

plugins:
  - serverless-api-gateway-throttling
custom:
  # Configures throttling settings for the API Gateway stage
  # They apply to all http endpoints, unless specifically overridden
  apiGatewayThrottling:
    maxRequestsPerSecond: 1
    maxConcurrentRequests: 3

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - rekognition:DetectLabels
          Resource: "*"
        - Effect: "Allow"
          Action:
            - translate:TranslateText
          Resource: "*"

functions:
  img-analisys:
    handler: handler.main
    events: 
      - http:
          path: hello
          method: get
